name: boarding_progress
description: A standard flutter package.
version: 0.0.0
homepage: https://github.com/Iconica-Development/boarding_progress

publish_to: none
environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  stepper:
    git: 
      url: https://github.com/Iconica-Development/stepper.git
      ref: v-0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
